#!/bin/bash
#
#
#     Copyright (C) 2012 Savoir-Faire Linux Inc. 
#
#     This program is free software; you can redistribute it and/or modify 
#     it under the terms of the GNU General Public License as published by 
#     the Free Software Foundation; either version 3 of the License, or 
#     (at your option) any later version. 
#
#     This program is distributed in the hope that it will be useful, 
#     but WITHOUT ANY WARRANTY; without even the implied warranty of 
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
#     GNU General Public License for more details. 
#
#     You should have received a copy of the GNU General Public License 
#     along with this program; if not, write to the Free Software 
#     Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. 
#
#     Projects :
#               SFL Shinken plugins
#
#     File :
#               runtests Launch unit tests
#
#
#     Author: <author_name> <<author_email>> 
#

TESTLIST=$1
TESTLIST=$(readlink -f $TESTLIST)

DIR=$(cd $(dirname "$0"); pwd)
#cd ${DIR}/..
echo `pwd`

rm -rf /tmp/shcov
rm -rf test/htmlcov

function launch_and_assert {
    SCRIPT=$1
    test/jenkins/shcov/shcov.py ./test/$SCRIPT
    if [ $? != 0 ]
    then
        echo "Error : the test $SCRIPT failed"
        exit 2
    else
        echo "test $SCRIPT succeeded, next one"
    fi
    mv test_results.xml test/TEST-$SCRIPT.xml
}


while read tfile
do
  case ${tfile:0:1} in
  "#")
       ;;
  *)   launch_and_assert $tfile
       ;;
  esac
done < $TESTLIST

sleep 3

find /tmp/shcov -name "shunit2*.pkl" -exec rm {} \;
find /tmp/shcov -name "test_*.pkl" -exec rm {} \;

test/jenkins/shcov/shlcov /tmp/shcov/ test/htmlcov
cp test/jenkins/shcov/data/* test/htmlcov/
