#!/bin/sh
#
#
#     Copyright (C) 2012 Savoir-Faire Linux Inc. 
#
#     This program is free software; you can redistribute it and/or modify 
#     it under the terms of the GNU General Public License as published by 
#     the Free Software Foundation; either version 3 of the License, or 
#     (at your option) any later version. 
#
#     This program is distributed in the hope that it will be useful, 
#     but WITHOUT ANY WARRANTY; without even the implied warranty of 
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
#     GNU General Public License for more details. 
#
#     You should have received a copy of the GNU General Public License 
#     along with this program; if not, write to the Free Software 
#     Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. 
#
#     Projects :
#               SFL Shinken plugins
#
#     File :
#               check_cpu.sh Plugin to check CPU usage
#
#
#     Author: Thibault Cohen <thibault.cohen@savoirfairelinux.com> 
#
#

PROGPATH="$(cd $(dirname "$0"); pwd)"

if [ -e $PROGPATH/check_cpu_utils.sh ]
then
    . $PROGPATH/check_cpu_utils.sh
elif [ -e ./check_cpu_utils.sh ]
then
    . ./check_cpu_utils.sh
else
    echo "UNKNOWN : check_cpu_utils.sh not found"
    exit 1
fi

if [ -e $PROGPATH/check_cpu.inc ]
then
    . $PROGPATH/check_cpu.inc
elif [ -e ./check_cpu.inc ]
then
    . ./check_cpu.inc
else
    echo "UNKNOWN : check_cpu.inc not found"
    exit 1
fi

#############################################
#                                           #
#    Return output and exit code            #
#                                           #
#############################################

while getopts "hv:w:c:i:v:" opt
do
    case "$opt" in
        v)
            alert=$OPTARG
        ;;
        w)
            warning=$OPTARG
        ;;
        c)
            critical=$OPTARG
        ;;
        h)
            print_help
            exit 3
        ;;
        v)
            print_revision $PROGNAME $REVISION
            exit 3
        ;;
        i)
            interval=$OPTARG
        ;;
        \?)
            print_help
            exit 3
        ;;
        :)
            # maybe useless
            echo "Option -$OPTARG requires an argument." >&2
            print_help
        ;;
    esac
done

check_arguments

get_data

